// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalType.proto

package via.sdj3.slaughterhouse.protobuf.animaltype;

public final class AnimalType {
  private AnimalType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_CreateAnimalTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_CreateAnimalTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_CreateAnimalTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_CreateAnimalTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_GetAnimalTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_GetAnimalTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_GetAnimalTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_GetAnimalTypeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020AnimalType.proto\022+via.sdj3.slaughterho" +
      "use.protobuf.animaltype\"<\n\027CreateAnimalT" +
      "ypeRequest\022\014\n\004name\030\001 \001(\t\022\023\n\013description\030" +
      "\002 \001(\t\"0\n\030CreateAnimalTypeResponse\022\024\n\014con" +
      "firmation\030\001 \001(\t\"\"\n\024GetAnimalTypeRequest\022" +
      "\n\n\002id\030\001 \001(\005\"F\n\025GetAnimalTypeResponse\022\n\n\002" +
      "id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 " +
      "\001(\t2\316\002\n\021AnimalTypeService\022\237\001\n\020createAnim" +
      "alType\022D.via.sdj3.slaughterhouse.protobu" +
      "f.animaltype.CreateAnimalTypeRequest\032E.v" +
      "ia.sdj3.slaughterhouse.protobuf.animalty" +
      "pe.CreateAnimalTypeResponse\022\226\001\n\rgetAnima" +
      "lType\022A.via.sdj3.slaughterhouse.protobuf" +
      ".animaltype.GetAnimalTypeRequest\032B.via.s" +
      "dj3.slaughterhouse.protobuf.animaltype.G" +
      "etAnimalTypeResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_CreateAnimalTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_CreateAnimalTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_CreateAnimalTypeRequest_descriptor,
        new java.lang.String[] { "Name", "Description", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_CreateAnimalTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_CreateAnimalTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_CreateAnimalTypeResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_GetAnimalTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_GetAnimalTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_GetAnimalTypeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_GetAnimalTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_GetAnimalTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animaltype_GetAnimalTypeResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
