// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalType.proto

package via.sdj3.slaughterhouse.protobuf.animaltype;

public interface GetAnimalTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.animaltype.GetAnimalTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
