// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Farm.proto

package via.sdj3.slaughterhouse.protobuf.farm;

public final class Farm {
  private Farm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_farm_CreateFarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_farm_CreateFarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_farm_CreateFarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_farm_CreateFarmResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_farm_GetFarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_farm_GetFarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_farm_GetFarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_farm_GetFarmResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nFarm.proto\022%via.sdj3.slaughterhouse.pr" +
      "otobuf.farm\"G\n\021CreateFarmRequest\022\014\n\004name" +
      "\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\017\n\007address\030\003" +
      " \001(\t\"*\n\022CreateFarmResponse\022\024\n\014confirmati" +
      "on\030\001 \001(\t\"\034\n\016GetFarmRequest\022\n\n\002id\030\001 \001(\005\"Q" +
      "\n\017GetFarmResponse\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 " +
      "\001(\t\022\023\n\013description\030\003 \001(\t\022\017\n\007address\030\004 \001(" +
      "\t2\213\002\n\013FarmService\022\201\001\n\ncreateFarm\0228.via.s" +
      "dj3.slaughterhouse.protobuf.farm.CreateF" +
      "armRequest\0329.via.sdj3.slaughterhouse.pro" +
      "tobuf.farm.CreateFarmResponse\022x\n\007getFarm" +
      "\0225.via.sdj3.slaughterhouse.protobuf.farm" +
      ".GetFarmRequest\0326.via.sdj3.slaughterhous" +
      "e.protobuf.farm.GetFarmResponseB\002P\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_via_sdj3_slaughterhouse_protobuf_farm_CreateFarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_via_sdj3_slaughterhouse_protobuf_farm_CreateFarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_farm_CreateFarmRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "Address", });
    internal_static_via_sdj3_slaughterhouse_protobuf_farm_CreateFarmResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_via_sdj3_slaughterhouse_protobuf_farm_CreateFarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_farm_CreateFarmResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_via_sdj3_slaughterhouse_protobuf_farm_GetFarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_via_sdj3_slaughterhouse_protobuf_farm_GetFarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_farm_GetFarmRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_via_sdj3_slaughterhouse_protobuf_farm_GetFarmResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_via_sdj3_slaughterhouse_protobuf_farm_GetFarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_farm_GetFarmResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
