// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Farm.proto

package via.sdj3.slaughterhouse.protobuf.farm;

public interface GetFarmRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.farm.GetFarmRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
