// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Store.proto

package via.sdj3.slaughterhouse.protobuf.store;

public interface CreateStoreRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.store.CreateStoreRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string address = 3;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 3;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>repeated int32 productIds = 4;</code>
   * @return A list containing the productIds.
   */
  java.util.List<java.lang.Integer> getProductIdsList();
  /**
   * <code>repeated int32 productIds = 4;</code>
   * @return The count of productIds.
   */
  int getProductIdsCount();
  /**
   * <code>repeated int32 productIds = 4;</code>
   * @param index The index of the element to return.
   * @return The productIds at the given index.
   */
  int getProductIds(int index);
}
