// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Store.proto

package via.sdj3.slaughterhouse.protobuf.store;

public interface GetStoreRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.store.GetStoreRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
