// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Store.proto

package via.sdj3.slaughterhouse.protobuf.store;

public final class Store {
  private Store() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_store_CreateStoreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_store_CreateStoreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_store_CreateStoreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_store_CreateStoreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_store_GetStoreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_store_GetStoreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_store_GetStoreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_store_GetStoreResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Store.proto\022&via.sdj3.slaughterhouse.p" +
      "rotobuf.store\"\\\n\022CreateStoreRequest\022\014\n\004n" +
      "ame\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\017\n\007addres" +
      "s\030\003 \001(\t\022\022\n\nproductIds\030\004 \003(\005\"+\n\023CreateSto" +
      "reResponse\022\024\n\014confirmation\030\001 \001(\t\"\035\n\017GetS" +
      "toreRequest\022\n\n\002id\030\001 \001(\005\"f\n\020GetStoreRespo" +
      "nse\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\023\n\013descrip" +
      "tion\030\003 \001(\t\022\017\n\007address\030\004 \001(\t\022\022\n\nproductId" +
      "s\030\005 \003(\0052\226\002\n\014StoreService\022\206\001\n\013CreateStore" +
      "\022:.via.sdj3.slaughterhouse.protobuf.stor" +
      "e.CreateStoreRequest\032;.via.sdj3.slaughte" +
      "rhouse.protobuf.store.CreateStoreRespons" +
      "e\022}\n\010GetStore\0227.via.sdj3.slaughterhouse." +
      "protobuf.store.GetStoreRequest\0328.via.sdj" +
      "3.slaughterhouse.protobuf.store.GetStore" +
      "ResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_via_sdj3_slaughterhouse_protobuf_store_CreateStoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_via_sdj3_slaughterhouse_protobuf_store_CreateStoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_store_CreateStoreRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "Address", "ProductIds", });
    internal_static_via_sdj3_slaughterhouse_protobuf_store_CreateStoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_via_sdj3_slaughterhouse_protobuf_store_CreateStoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_store_CreateStoreResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_via_sdj3_slaughterhouse_protobuf_store_GetStoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_via_sdj3_slaughterhouse_protobuf_store_GetStoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_store_GetStoreRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_via_sdj3_slaughterhouse_protobuf_store_GetStoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_via_sdj3_slaughterhouse_protobuf_store_GetStoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_store_GetStoreResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Address", "ProductIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
