// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package via.sdj3.slaughterhouse.protobuf.animal;

public final class Animal {
  private Animal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_CreateAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animal_CreateAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_CreateAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animal_CreateAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalIdsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Animal.proto\022\'via.sdj3.slaughterhouse." +
      "protobuf.animal\"v\n\023CreateAnimalRequest\022\016" +
      "\n\006farmId\030\001 \001(\005\022\024\n\014animalTypeId\030\002 \001(\005\022\016\n\006" +
      "weight\030\003 \001(\001\022\030\n\020registrationDate\030\004 \001(\t\022\017" +
      "\n\007healthy\030\005 \001(\010\",\n\024CreateAnimalResponse\022" +
      "\024\n\014confirmation\030\001 \001(\t\"$\n\020GetAnimalReques" +
      "t\022\020\n\010animalId\030\001 \001(\005\"\206\001\n\021GetAnimalRespons" +
      "e\022\020\n\010animalId\030\001 \001(\005\022\016\n\006farmId\030\002 \001(\005\022\024\n\014a" +
      "nimalTypeId\030\003 \001(\005\022\016\n\006weight\030\004 \001(\001\022\030\n\020reg" +
      "istrationDate\030\005 \001(\t\022\017\n\007healthy\030\006 \001(\010\"(\n\023" +
      "GetAnimalIdsRequest\022\021\n\tproductId\030\001 \001(\005\")" +
      "\n\024GetAnimalIdsResponse\022\021\n\tanimalIds\030\001 \003(" +
      "\0052\260\003\n\rAnimalService\022\213\001\n\014createAnimal\022<.v" +
      "ia.sdj3.slaughterhouse.protobuf.animal.C" +
      "reateAnimalRequest\032=.via.sdj3.slaughterh" +
      "ouse.protobuf.animal.CreateAnimalRespons" +
      "e\022\202\001\n\tgetAnimal\0229.via.sdj3.slaughterhous" +
      "e.protobuf.animal.GetAnimalRequest\032:.via" +
      ".sdj3.slaughterhouse.protobuf.animal.Get" +
      "AnimalResponse\022\213\001\n\014getAnimalIds\022<.via.sd" +
      "j3.slaughterhouse.protobuf.animal.GetAni" +
      "malIdsRequest\032=.via.sdj3.slaughterhouse." +
      "protobuf.animal.GetAnimalIdsResponseB\002P\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_CreateAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_CreateAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animal_CreateAnimalRequest_descriptor,
        new java.lang.String[] { "FarmId", "AnimalTypeId", "Weight", "RegistrationDate", "Healthy", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_CreateAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_CreateAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animal_CreateAnimalResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalRequest_descriptor,
        new java.lang.String[] { "AnimalId", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalResponse_descriptor,
        new java.lang.String[] { "AnimalId", "FarmId", "AnimalTypeId", "Weight", "RegistrationDate", "Healthy", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animal_GetAnimalIdsResponse_descriptor,
        new java.lang.String[] { "AnimalIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
