// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package via.sdj3.slaughterhouse.protobuf.animal;

public interface GetAnimalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.animal.GetAnimalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 animalId = 1;</code>
   * @return The animalId.
   */
  int getAnimalId();
}
