// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package via.sdj3.slaughterhouse.protobuf.animal;

public interface GetAnimalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.animal.GetAnimalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 animalId = 1;</code>
   * @return The animalId.
   */
  int getAnimalId();

  /**
   * <code>int32 animalTypeId = 2;</code>
   * @return The animalTypeId.
   */
  int getAnimalTypeId();

  /**
   * <code>double weight = 3;</code>
   * @return The weight.
   */
  double getWeight();

  /**
   * <code>string registrationDate = 4;</code>
   * @return The registrationDate.
   */
  java.lang.String getRegistrationDate();
  /**
   * <code>string registrationDate = 4;</code>
   * @return The bytes for registrationDate.
   */
  com.google.protobuf.ByteString
      getRegistrationDateBytes();

  /**
   * <code>bool healthy = 5;</code>
   * @return The healthy.
   */
  boolean getHealthy();
}
