// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package via.sdj3.slaughterhouse.protobuf.animal;

public interface GetAnimalIdsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.animal.GetAnimalIdsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 productId = 1;</code>
   * @return The productId.
   */
  int getProductId();
}
