// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package via.sdj3.slaughterhouse.protobuf.animal;

public interface GetAnimalIdsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.animal.GetAnimalIdsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 animalIds = 1;</code>
   * @return A list containing the animalIds.
   */
  java.util.List<java.lang.Integer> getAnimalIdsList();
  /**
   * <code>repeated int32 animalIds = 1;</code>
   * @return The count of animalIds.
   */
  int getAnimalIdsCount();
  /**
   * <code>repeated int32 animalIds = 1;</code>
   * @param index The index of the element to return.
   * @return The animalIds at the given index.
   */
  int getAnimalIds(int index);
}
