// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalPart.proto

package via.sdj3.slaughterhouse.protobuf.animalpart;

public final class AnimalPart {
  private AnimalPart() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_CreateAnimalPartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_CreateAnimalPartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_CreateAnimalPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_CreateAnimalPartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_GetAnimalPartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_GetAnimalPartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_GetAnimalPartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_GetAnimalPartResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020AnimalPart.proto\022+via.sdj3.slaughterho" +
      "use.protobuf.animalpart\"e\n\027CreateAnimalP" +
      "artRequest\022\016\n\006weight\030\001 \001(\001\022\020\n\010animalId\030\002" +
      " \001(\005\022\016\n\006trayId\030\003 \001(\005\022\030\n\020animalPartTypeId" +
      "\030\004 \001(\005\"0\n\030CreateAnimalPartResponse\022\024\n\014co" +
      "nfirmation\030\001 \001(\t\"\"\n\024GetAnimalPartRequest" +
      "\022\n\n\002id\030\001 \001(\005\"E\n\025GetAnimalPartResponse\022\n\n" +
      "\002id\030\001 \001(\005\022\016\n\006weight\030\002 \001(\001\022\020\n\010animalId\030\003 " +
      "\001(\0052\316\002\n\021AnimalPartService\022\237\001\n\020createAnim" +
      "alPart\022D.via.sdj3.slaughterhouse.protobu" +
      "f.animalpart.CreateAnimalPartRequest\032E.v" +
      "ia.sdj3.slaughterhouse.protobuf.animalpa" +
      "rt.CreateAnimalPartResponse\022\226\001\n\rgetAnima" +
      "lPart\022A.via.sdj3.slaughterhouse.protobuf" +
      ".animalpart.GetAnimalPartRequest\032B.via.s" +
      "dj3.slaughterhouse.protobuf.animalpart.G" +
      "etAnimalPartResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_CreateAnimalPartRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_CreateAnimalPartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_CreateAnimalPartRequest_descriptor,
        new java.lang.String[] { "Weight", "AnimalId", "TrayId", "AnimalPartTypeId", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_CreateAnimalPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_CreateAnimalPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_CreateAnimalPartResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_GetAnimalPartRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_GetAnimalPartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_GetAnimalPartRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_GetAnimalPartResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_GetAnimalPartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animalpart_GetAnimalPartResponse_descriptor,
        new java.lang.String[] { "Id", "Weight", "AnimalId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
