// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalPart.proto

package via.sdj3.slaughterhouse.protobuf.animalpart;

public interface GetAnimalPartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.animalpart.GetAnimalPartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>double weight = 2;</code>
   * @return The weight.
   */
  double getWeight();

  /**
   * <code>int32 animalId = 3;</code>
   * @return The animalId.
   */
  int getAnimalId();
}
