// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalPart.proto

package via.sdj3.slaughterhouse.protobuf.animalpart;

public interface GetAnimalPartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.animalpart.GetAnimalPartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
