// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package via.sdj3.slaughterhouse.protobuf.product;

public interface GetProductIdsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.product.GetProductIdsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 animalId = 1;</code>
   * @return The animalId.
   */
  int getAnimalId();
}
