// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package via.sdj3.slaughterhouse.protobuf.product;

public interface GetProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.product.GetProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
