// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package via.sdj3.slaughterhouse.protobuf.product;

public interface GetProductsIdsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.product.GetProductsIdsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 productIds = 1;</code>
   * @return A list containing the productIds.
   */
  java.util.List<java.lang.Integer> getProductIdsList();
  /**
   * <code>repeated int32 productIds = 1;</code>
   * @return The count of productIds.
   */
  int getProductIdsCount();
  /**
   * <code>repeated int32 productIds = 1;</code>
   * @param index The index of the element to return.
   * @return The productIds at the given index.
   */
  int getProductIds(int index);
}
