// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalPartType.proto

package via.sdj3.slaughterhouse.protobuf.animalparttype;

public final class AnimalPartType {
  private AnimalPartType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024AnimalPartType.proto\022/via.sdj3.slaught" +
      "erhouse.protobuf.animalparttype\"@\n\033Creat" +
      "eAnimalPartTypeRequest\022\014\n\004name\030\001 \001(\t\022\023\n\013" +
      "description\030\002 \001(\t\"4\n\034CreateAnimalPartTyp" +
      "eResponse\022\024\n\014confirmation\030\001 \001(\t\"&\n\030GetAn" +
      "imalPartTypeRequest\022\n\n\002id\030\001 \001(\005\"J\n\031GetAn" +
      "imalPartTypeResponse\022\n\n\002id\030\001 \001(\005\022\014\n\004name" +
      "\030\002 \001(\t\022\023\n\013description\030\003 \001(\t2\372\002\n\025AnimalPa" +
      "rtTypeService\022\263\001\n\024CreateAnimalPartType\022L" +
      ".via.sdj3.slaughterhouse.protobuf.animal" +
      "parttype.CreateAnimalPartTypeRequest\032M.v" +
      "ia.sdj3.slaughterhouse.protobuf.animalpa" +
      "rttype.CreateAnimalPartTypeResponse\022\252\001\n\021" +
      "GetAnimalPartType\022I.via.sdj3.slaughterho" +
      "use.protobuf.animalparttype.GetAnimalPar" +
      "tTypeRequest\032J.via.sdj3.slaughterhouse.p" +
      "rotobuf.animalparttype.GetAnimalPartType" +
      "ResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeRequest_descriptor,
        new java.lang.String[] { "Name", "Description", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
