// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalPartType.proto

package via.sdj3.slaughterhouse.protobuf.animalparttype;

public interface CreateAnimalPartTypeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.animalparttype.CreateAnimalPartTypeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmation = 1;</code>
   * @return The confirmation.
   */
  java.lang.String getConfirmation();
  /**
   * <code>string confirmation = 1;</code>
   * @return The bytes for confirmation.
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
