// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalPartType.proto

package via.sdj3.slaughterhouse.protobuf.animalparttype;

public interface GetAnimalPartTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.animalparttype.GetAnimalPartTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
