// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tray.proto

package via.sdj3.slaughterhouse.protobuf.tray;

public interface GetTrayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.tray.GetTrayResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>double weight = 3;</code>
   * @return The weight.
   */
  double getWeight();

  /**
   * <code>repeated int32 animalPartIds = 4;</code>
   * @return A list containing the animalPartIds.
   */
  java.util.List<java.lang.Integer> getAnimalPartIdsList();
  /**
   * <code>repeated int32 animalPartIds = 4;</code>
   * @return The count of animalPartIds.
   */
  int getAnimalPartIdsCount();
  /**
   * <code>repeated int32 animalPartIds = 4;</code>
   * @param index The index of the element to return.
   * @return The animalPartIds at the given index.
   */
  int getAnimalPartIds(int index);
}
