// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tray.proto

package via.sdj3.slaughterhouse.protobuf.tray;

public interface GetTrayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:via.sdj3.slaughterhouse.protobuf.tray.GetTrayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
