// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tray.proto

package via.sdj3.slaughterhouse.protobuf.tray;

public final class Tray {
  private Tray() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_tray_CreateTrayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_tray_CreateTrayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_tray_CreateTrayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_tray_CreateTrayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_tray_GetTrayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_tray_GetTrayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_via_sdj3_slaughterhouse_protobuf_tray_GetTrayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_via_sdj3_slaughterhouse_protobuf_tray_GetTrayResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTray.proto\022%via.sdj3.slaughterhouse.pr" +
      "otobuf.tray\"O\n\021CreateTrayRequest\022\023\n\013desc" +
      "ription\030\001 \001(\t\022\016\n\006weight\030\002 \001(\001\022\025\n\ranimalP" +
      "artIds\030\003 \003(\005\"*\n\022CreateTrayResponse\022\024\n\014co" +
      "nfirmation\030\001 \001(\t\"\034\n\016GetTrayRequest\022\n\n\002id" +
      "\030\001 \001(\005\"Y\n\017GetTrayResponse\022\n\n\002id\030\001 \001(\005\022\023\n" +
      "\013description\030\002 \001(\t\022\016\n\006weight\030\003 \001(\001\022\025\n\ran" +
      "imalPartIds\030\004 \003(\0052\213\002\n\013TrayService\022\201\001\n\nCr" +
      "eateTray\0228.via.sdj3.slaughterhouse.proto" +
      "buf.tray.CreateTrayRequest\0329.via.sdj3.sl" +
      "aughterhouse.protobuf.tray.CreateTrayRes" +
      "ponse\022x\n\007GetTray\0225.via.sdj3.slaughterhou" +
      "se.protobuf.tray.GetTrayRequest\0326.via.sd" +
      "j3.slaughterhouse.protobuf.tray.GetTrayR" +
      "esponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_via_sdj3_slaughterhouse_protobuf_tray_CreateTrayRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_via_sdj3_slaughterhouse_protobuf_tray_CreateTrayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_tray_CreateTrayRequest_descriptor,
        new java.lang.String[] { "Description", "Weight", "AnimalPartIds", });
    internal_static_via_sdj3_slaughterhouse_protobuf_tray_CreateTrayResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_via_sdj3_slaughterhouse_protobuf_tray_CreateTrayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_tray_CreateTrayResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_via_sdj3_slaughterhouse_protobuf_tray_GetTrayRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_via_sdj3_slaughterhouse_protobuf_tray_GetTrayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_tray_GetTrayRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_via_sdj3_slaughterhouse_protobuf_tray_GetTrayResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_via_sdj3_slaughterhouse_protobuf_tray_GetTrayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_via_sdj3_slaughterhouse_protobuf_tray_GetTrayResponse_descriptor,
        new java.lang.String[] { "Id", "Description", "Weight", "AnimalPartIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
